export { default as DutyFreeShopping } from './icons/duty-free-shopping';
export { default as InstaxTaxRefund } from './icons/instax-tax-refund';
export { default as Authentic } from './icons/authentic';
export { default as GlobalGuarantee } from './icons/global-guarantee';
export { default as BeautyConciergeService } from './icons/beauty-concierge-service';
export { default as SpaMassage } from './icons/spa-massage';
export { default as MemberExclsuiveDelivery } from './icons/member-exclsuive-delivery';
export { default as ClickCollect } from './icons/click-collect';
export { default as PersonalShopper } from './icons/personal-shopper';
